# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy all source files
COPY . .

# Expose port if needed (optional) 

# Start the GitHub MCP server
CMD [ "node", "mcp-servers/github/index.js" ]
