# This file controls the behavior of the Supabase CLI
# Reference: https://supabase.com/docs/guides/cli/config

[project]
# Project reference
# reference = "<PROJECT_ID>"

[api]
# Port number for the local API server
port = 54321
# Additional flags passed to the API server command
# extra_flags = []

[db]
# Port number for the local database
port = 54322
# Include database password
shadow_database_port = 54320
major_version = 15

[studio]
# Port number for the Studio server
port = 54323

[functions]
# Forward request headers to invoked functions
forward_request_headers = false

[inbucket]
# Port number for the local email testing server web interface
port = 54324

[storage]
# Port number for the local storage server
port = 54325

[auth]
# Enable JWT verification for function authorization
enable_function_verification = true 